# Generated by Django 2.2.7 on 2019-11-26 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0002_auto_20191126_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertView',
            new_name='Alert',
        ),
    ]
